### ISSUE TITLE
Calculate AQI using PM10 and 2.5

### ISSUE THREAD

**Issue by BaiqingL** [ThangLeQuoc/aqi-calculator#54]
I see from the example of calculating AQI by passing in a PM10 value, for my specifications I am given PM2.5 and PM10 data, is there a formula to calculate AQI given those two values?

Thanks!

**Comment by thanglequoc** [comment]
Hi @BaiqingL , 
Thank for droping by,

It's depend on the type of calculation strategy you used to display the AQI.

**Use the Nowcast AQI Calculation strategy**, for real-time readings and readings less than 6 hours old.

Once you have enough data more than 6 hours old of a particular hours, use the average 12 hours strategy with the regular AQI Calculation strategy, see section [Hourly PM2.5 AQI](https://forum.airnowtech.org/t/daily-and-hourly-aqi-pm2-5/171)

Once you have enough data in the day, use the average concentration in day with the regular AQI calculation strategy to calculate the daily AQI.

Reference: https://forum.airnowtech.org/t/daily-and-hourly-aqi-pm2-5/171

**Comment by BaiqingL** [comment]
Thanks! I figured it out :)
